name: Continuous Integration

on:
  push:
    branches:
      - master
      - main
      - develop
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    name: node-${{ matrix.node }}
    strategy:
      matrix:
        node: [18, 20]
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Validate
        run: npm run ci

      - name: Build
        run: npm run build
